spring.application.name=ChernobylExclusionExplorer

# --- CONFIGURACION DE BASE DE DATOS FISICA (PERSISTENTE) ---
spring.datasource.url=jdbc:h2:file:./data/cherno;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# --- COMPORTAMIENTO DE HIBERNATE ---
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# --- CONSOLA H2 ---
spring.h2.console.path=/h2-console
spring.h2.console.enabled=true

# --- CARGA DEL ARCHIVO DATA.SQL ---
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# ESTO ES LO QUE ARREGLA EL ARRANQUE: Ignora el error de que el usuario ya existe y sigue adelante.
spring.sql.init.continue-on-error=false

# --- CONFIGURACION DEL SERVIDOR ---
server.port=8080
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.mvc.pathmatch.matching-strategy=ant_path_matcher